import { storage } from "./storage-db";
import type { InsertCategory, InsertService, InsertSiteContent } from "@shared/schema";

const categories: InsertCategory[] = [
  {
    slug: "business-registration",
    name: "Business Registration & Legal",
    description: "Complete business setup including registration, licenses, and legal documentation",
    sortOrder: 1,
  },
  {
    slug: "financial-compliance",
    name: "Financial & Compliance",
    description: "Banking, accounting, GST, tax filing, and financial compliance services",
    sortOrder: 2,
  },
  {
    slug: "digital-marketing",
    name: "Digital Marketing",
    description: "Website development, SEO, social media, and online advertising",
    sortOrder: 3,
  },
  {
    slug: "operations-logistics",
    name: "Operations & Logistics",
    description: "Vendor management, inventory, courier partners, and office setup",
    sortOrder: 4,
  },
  {
    slug: "hr-team",
    name: "HR & Team Building",
    description: "Recruitment, onboarding, HR compliance, and employee management",
    sortOrder: 5,
  },
  {
    slug: "growth-funding",
    name: "Growth & Funding",
    description: "Investor pitches, funding, market research, and scaling strategies",
    sortOrder: 6,
  },
  {
    slug: "industry-specific",
    name: "Industry-Specific Services",
    description: "Specialized licenses and permits for food, healthcare, manufacturing, and more",
    sortOrder: 7,
  },
  {
    slug: "risk-insurance",
    name: "Risk & Insurance",
    description: "Business insurance, audits, and exit planning",
    sortOrder: 8,
  },
];

export async function seedDatabase() {
  const existingCategories = await storage.getAllCategories();
  if (existingCategories.length > 0) {
    console.log("✓ Database already seeded");
    return;
  }

  console.log("Seeding database...");

  const createdCategories = await Promise.all(
    categories.map((cat) => storage.createCategory(cat))
  );

  const categoryMap = Object.fromEntries(
    createdCategories.map((cat) => [cat.slug, cat.id])
  );

  const services: InsertService[] = [
    {
      categoryId: categoryMap["business-registration"],
      slug: "business-idea-validation",
      name: "Business Idea Validation & Structuring Advice",
      summary: "Expert analysis and validation of your business concept with structure recommendations",
      longDescription: "Comprehensive evaluation of business viability • Market opportunity assessment • Business structure recommendations",
      basePriceInr: "2999",
      etaDays: 3,
      icon: "Lightbulb",
      active: true,
      problem: "Uncertain if your business idea is viable or which structure suits you best",
      outcome: "Clear validation report with recommended business structure and next steps",
      includes: "Market analysis • Competitor research • Structure comparison (Proprietorship vs LLP vs Pvt Ltd)",
      prerequisites: "Business idea description • Target market information",
      timeline: "3 days from information submission",
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "proprietorship-setup",
      name: "Proprietorship Firm Setup",
      summary: "Complete setup of sole proprietorship with all necessary registrations",
      longDescription: "Full proprietorship registration • PAN and bank account assistance • Basic compliance setup",
      basePriceInr: "1999",
      etaDays: 5,
      icon: "User",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "partnership-deed",
      name: "Partnership Firm Deed & Registration",
      summary: "Partnership deed drafting and firm registration with stamp duty filing",
      longDescription: "Partnership deed drafting • Stamp duty payment • Partnership firm registration",
      basePriceInr: "4999",
      etaDays: 7,
      icon: "Users",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "llp-incorporation",
      name: "Limited Liability Partnership (LLP) Incorporation",
      summary: "Complete LLP registration with DPIN, DIN, and incorporation certificate",
      longDescription: "Name approval (RUN) • DPIN & DIN allotment • LLP Agreement drafting • Certificate of Incorporation",
      basePriceInr: "8999",
      etaDays: 7,
      icon: "Building2",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "pvt-ltd-incorporation",
      name: "Private Limited Company Incorporation",
      summary: "End-to-end private limited company registration with all compliances",
      longDescription: "Name reservation (SPICe+) • DIN & DSC • MOA & AOA filing • Incorporation certificate",
      basePriceInr: "12999",
      etaDays: 10,
      icon: "Building",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "opc-incorporation",
      name: "One Person Company (OPC) Incorporation",
      summary: "Single-member company registration with limited liability benefits",
      longDescription: "Name approval • Director DSC & DIN • Company incorporation • PAN & TAN allotment",
      basePriceInr: "10999",
      etaDays: 8,
      icon: "UserCog",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "din-application",
      name: "Director Identification Number (DIN)",
      summary: "DIN application for company directors",
      longDescription: "DIN application filing • Document verification • DIN allotment certificate",
      basePriceInr: "999",
      etaDays: 3,
      icon: "IdCard",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "dsc-certificate",
      name: "Digital Signature Certificate (DSC)",
      summary: "Class 3 DSC for company filings and e-tenders",
      longDescription: "DSC application • Document verification • 2-year validity certificate",
      basePriceInr: "1499",
      etaDays: 2,
      icon: "FileSignature",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "business-pan",
      name: "Business PAN Card Application",
      summary: "PAN card application for businesses and entities",
      longDescription: "PAN application filing • Document submission • PAN card delivery",
      basePriceInr: "799",
      etaDays: 7,
      icon: "CreditCard",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "tan-application",
      name: "Tax Deduction Account Number (TAN)",
      summary: "TAN registration for businesses deducting TDS",
      longDescription: "TAN application • Verification • TAN allotment certificate",
      basePriceInr: "999",
      etaDays: 5,
      icon: "Receipt",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "shop-establishment",
      name: "Shop & Establishment License",
      summary: "Mandatory shop registration under state Shop Act",
      longDescription: "Application preparation • Document filing • License certificate",
      basePriceInr: "2499",
      etaDays: 10,
      icon: "Store",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "udyam-registration",
      name: "Udyam (MSME) Registration",
      summary: "MSME registration for accessing government benefits and schemes",
      longDescription: "Udyam registration • Classification (Micro/Small/Medium) • Certificate generation",
      basePriceInr: "1999",
      etaDays: 3,
      icon: "Factory",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "trademark-filing",
      name: "Trademark Search & Filing (Name/Logo)",
      summary: "Comprehensive trademark search and application filing for brand protection",
      longDescription: "Trademark search (similar marks) • Class identification • Filing & tracking",
      basePriceInr: "5999",
      etaDays: 10,
      icon: "Shield",
      active: true,
    },
    {
      categoryId: categoryMap["business-registration"],
      slug: "copyright-registration",
      name: "Copyright Registration (Content/Creative)",
      summary: "Copyright protection for original creative works",
      longDescription: "Copyright search • Application filing • Registration certificate",
      basePriceInr: "4999",
      etaDays: 90,
      icon: "Copyright",
      active: true,
    },

    {
      categoryId: categoryMap["financial-compliance"],
      slug: "gst-registration",
      name: "GST Registration & GSTIN Allotment",
      summary: "Complete GST registration with GSTIN and HSN/SAC classification",
      longDescription: "GST application • Document verification • GSTIN certificate",
      basePriceInr: "2499",
      etaDays: 5,
      icon: "FileText",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "gst-return-monthly",
      name: "Monthly GST Return Filing (GSTR-1, GSTR-3B)",
      summary: "Monthly GST returns preparation and filing",
      longDescription: "Invoice compilation • GSTR-1 & GSTR-3B preparation • Online filing",
      basePriceInr: "1499",
      etaDays: 3,
      icon: "Calendar",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "gst-return-annual",
      name: "GST Annual Return (GSTR-9)",
      summary: "Annual GST return consolidation and filing",
      longDescription: "Annual reconciliation • GSTR-9 preparation • Filing and tracking",
      basePriceInr: "4999",
      etaDays: 7,
      icon: "CalendarCheck",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "tds-filing",
      name: "TDS Return Filing (Form 26Q, 24Q)",
      summary: "Quarterly TDS return preparation and filing",
      longDescription: "TDS calculation • Return preparation • Online filing • TDS certificates",
      basePriceInr: "2999",
      etaDays: 5,
      icon: "ReceiptText",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "itr-filing-business",
      name: "Income Tax Return Filing for Business (ITR-3, ITR-4)",
      summary: "Business tax return filing with P&L and balance sheet",
      longDescription: "Financial statement preparation • ITR-3/ITR-4 filing • Tax computation",
      basePriceInr: "3999",
      etaDays: 7,
      icon: "FileCheck",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "bank-account-opening",
      name: "Business Bank Account Opening (Current A/C)",
      summary: "Assistance with business current account opening at major banks",
      longDescription: "Bank selection guidance • Documentation preparation • Account opening support",
      basePriceInr: "1999",
      etaDays: 7,
      icon: "Landmark",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "payment-gateway-integration",
      name: "Payment Gateway Integration (Razorpay, CCAvenue)",
      summary: "Payment gateway setup and integration for online payments",
      longDescription: "Gateway selection • Account setup • Technical integration • Testing",
      basePriceInr: "4999",
      etaDays: 5,
      icon: "CreditCard",
      active: true,
    },
    {
      categoryId: categoryMap["financial-compliance"],
      slug: "accounting-software-setup",
      name: "Accounting Software Setup (Tally, Zoho Books)",
      summary: "Complete accounting software installation and configuration",
      longDescription: "Software installation • Company setup • Chart of accounts • User training",
      basePriceInr: "3499",
      etaDays: 3,
      icon: "Calculator",
      active: true,
    },

    {
      categoryId: categoryMap["digital-marketing"],
      slug: "domain-registration",
      name: "Domain Name Registration (.in, .com)",
      summary: "Domain name search, registration, and setup",
      longDescription: "Domain availability check • Registration • DNS configuration",
      basePriceInr: "999",
      etaDays: 1,
      icon: "Globe",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "business-email-hosting",
      name: "Professional Business Email Hosting",
      summary: "Custom business email with your domain name",
      longDescription: "Email hosting setup • 10 email accounts • Spam protection",
      basePriceInr: "1999",
      etaDays: 2,
      icon: "Mail",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "website-5-page",
      name: "Basic 5-Page Website Development",
      summary: "Professional 5-page business website with responsive design",
      longDescription: "Custom design • 5 pages • Mobile responsive • Contact form • SEO ready",
      basePriceInr: "12999",
      etaDays: 14,
      icon: "Monitor",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "ecommerce-website",
      name: "E-commerce Website Development (Shopify, WooCommerce)",
      summary: "Full-featured online store with payment integration",
      longDescription: "Product catalog • Payment gateway • Inventory management • Order processing",
      basePriceInr: "24999",
      etaDays: 21,
      icon: "ShoppingCart",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "seo-audit",
      name: "Website SEO Audit & On-Page Optimization",
      summary: "Comprehensive SEO analysis and optimization",
      longDescription: "Technical SEO audit • Keyword research • On-page optimization • Performance report",
      basePriceInr: "7999",
      etaDays: 7,
      icon: "TrendingUp",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "google-my-business",
      name: "Google My Business Profile Setup & Verification",
      summary: "Local SEO optimization with Google Business Profile",
      longDescription: "Profile creation • Business verification • Optimization • Review management setup",
      basePriceInr: "1999",
      etaDays: 5,
      icon: "MapPin",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "social-media-setup",
      name: "Social Media Profile Setup (FB, Insta, LinkedIn, X)",
      summary: "Professional social media presence across major platforms",
      longDescription: "Profile creation (4 platforms) • Bio optimization • Cover & profile images • Initial posts",
      basePriceInr: "3999",
      etaDays: 5,
      icon: "Share2",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "google-ads-setup",
      name: "Google Ads (Search) Campaign Setup",
      summary: "Search advertising campaign with keyword targeting",
      longDescription: "Campaign strategy • Keyword research • Ad copy • Landing page optimization",
      basePriceInr: "8999",
      etaDays: 5,
      icon: "Search",
      active: true,
    },
    {
      categoryId: categoryMap["digital-marketing"],
      slug: "meta-ads-setup",
      name: "Meta (Facebook/Instagram) Ads Setup",
      summary: "Social media advertising campaign on Meta platforms",
      longDescription: "Audience targeting • Ad creative • Campaign setup • Performance tracking",
      basePriceInr: "7999",
      etaDays: 5,
      icon: "Facebook",
      active: true,
    },

    {
      categoryId: categoryMap["operations-logistics"],
      slug: "vendor-onboarding",
      name: "Vendor Identification & Onboarding",
      summary: "Finding and onboarding reliable vendors for your business",
      longDescription: "Vendor sourcing • Quote comparison • Agreement drafting • Onboarding",
      basePriceInr: "4999",
      etaDays: 10,
      icon: "Handshake",
      active: true,
    },
    {
      categoryId: categoryMap["operations-logistics"],
      slug: "inventory-management-setup",
      name: "Inventory Management System Setup",
      summary: "Digital inventory tracking and management system",
      longDescription: "Software selection • Setup & configuration • Stock tracking • User training",
      basePriceInr: "5999",
      etaDays: 7,
      icon: "Package",
      active: true,
    },
    {
      categoryId: categoryMap["operations-logistics"],
      slug: "courier-partner-onboarding",
      name: "Courier & Logistics Partner Onboarding (Delhivery, Shiprocket)",
      summary: "Integration with courier partners for shipping",
      longDescription: "Partner selection • Account setup • Rate negotiation • Integration",
      basePriceInr: "3499",
      etaDays: 5,
      icon: "Truck",
      active: true,
    },
    {
      categoryId: categoryMap["operations-logistics"],
      slug: "crm-setup",
      name: "CRM Software Setup (HubSpot, Zoho CRM)",
      summary: "Customer relationship management system implementation",
      longDescription: "CRM selection • Setup & customization • Pipeline configuration • Team training",
      basePriceInr: "6999",
      etaDays: 7,
      icon: "Users",
      active: true,
    },

    {
      categoryId: categoryMap["hr-team"],
      slug: "job-description-writing",
      name: "Job Description Writing",
      summary: "Professional JD creation for hiring",
      longDescription: "Role analysis • JD drafting • Skill requirements • Compensation benchmarking",
      basePriceInr: "1499",
      etaDays: 2,
      icon: "FileText",
      active: true,
    },
    {
      categoryId: categoryMap["hr-team"],
      slug: "employment-agreement",
      name: "Employment Agreement Drafting",
      summary: "Legally compliant employment contracts",
      longDescription: "Agreement drafting • Terms & conditions • Confidentiality clauses • Review",
      basePriceInr: "2999",
      etaDays: 3,
      icon: "FileSignature",
      active: true,
    },
    {
      categoryId: categoryMap["hr-team"],
      slug: "epf-registration",
      name: "Employee Provident Fund (EPF) Registration",
      summary: "EPF registration for employee benefits",
      longDescription: "EPF application • Employer & establishment registration • Login credentials",
      basePriceInr: "2499",
      etaDays: 7,
      icon: "PiggyBank",
      active: true,
    },
    {
      categoryId: categoryMap["hr-team"],
      slug: "esic-registration",
      name: "Employee State Insurance (ESIC) Registration",
      summary: "ESIC registration for employee health insurance",
      longDescription: "ESIC application • Code number allotment • Registration certificate",
      basePriceInr: "2499",
      etaDays: 7,
      icon: "Heart",
      active: true,
    },

    {
      categoryId: categoryMap["growth-funding"],
      slug: "pitch-deck-creation",
      name: "Investor Pitch Deck Creation",
      summary: "Professional investor presentation with financials",
      longDescription: "Market analysis • Business model • Financial projections • Design",
      basePriceInr: "14999",
      etaDays: 7,
      icon: "Presentation",
      active: true,
    },
    {
      categoryId: categoryMap["growth-funding"],
      slug: "financial-projections",
      name: "Financial Model & Projections (3-5 Years)",
      summary: "Detailed financial modeling and forecasting",
      longDescription: "Revenue projections • Cost analysis • Cash flow • Break-even analysis",
      basePriceInr: "9999",
      etaDays: 7,
      icon: "TrendingUp",
      active: true,
    },
    {
      categoryId: categoryMap["growth-funding"],
      slug: "market-research",
      name: "Market Research & Competitor Analysis",
      summary: "In-depth market study and competitive landscape",
      longDescription: "Market sizing • Competitor analysis • Customer insights • Opportunity identification",
      basePriceInr: "12999",
      etaDays: 10,
      icon: "BarChart",
      active: true,
    },
    {
      categoryId: categoryMap["growth-funding"],
      slug: "bank-loan-proposal",
      name: "Bank Loan Proposal & Application (Mudra, CGTMSE)",
      summary: "Complete loan application preparation and submission",
      longDescription: "Proposal drafting • Documentation • Application filing • Follow-up",
      basePriceInr: "7999",
      etaDays: 10,
      icon: "Building",
      active: true,
    },

    {
      categoryId: categoryMap["industry-specific"],
      slug: "fssai-license",
      name: "FSSAI License (Basic/State/Central)",
      summary: "Food business license for manufacturing or distribution",
      longDescription: "Application preparation • Documentation • License certificate",
      basePriceInr: "3999",
      etaDays: 15,
      icon: "UtensilsCrossed",
      active: true,
    },
    {
      categoryId: categoryMap["industry-specific"],
      slug: "import-export-code",
      name: "Import Export Code (IEC) Registration",
      summary: "IEC for import/export business activities",
      longDescription: "IEC application • Documentation • Code allotment",
      basePriceInr: "2999",
      etaDays: 7,
      icon: "Ship",
      active: true,
    },
    {
      categoryId: categoryMap["industry-specific"],
      slug: "marketplace-amazon",
      name: "Marketplace Account Setup (Amazon, Flipkart, Meesho)",
      summary: "Seller account setup on major e-commerce platforms",
      longDescription: "Account creation • Documentation • Catalog setup • Product listing",
      basePriceInr: "4999",
      etaDays: 7,
      icon: "ShoppingBag",
      active: true,
    },
    {
      categoryId: categoryMap["industry-specific"],
      slug: "pharmacy-license",
      name: "Pharmacy License",
      summary: "Drug license for pharmacy operations",
      longDescription: "Application preparation • Inspection support • License issuance",
      basePriceInr: "5999",
      etaDays: 20,
      icon: "Pill",
      active: true,
    },

    {
      categoryId: categoryMap["risk-insurance"],
      slug: "business-liability-insurance",
      name: "Business Liability Insurance",
      summary: "Comprehensive business liability coverage",
      longDescription: "Risk assessment • Policy comparison • Application • Premium support",
      basePriceInr: "3999",
      etaDays: 5,
      icon: "Shield",
      active: true,
    },
    {
      categoryId: categoryMap["risk-insurance"],
      slug: "statutory-audit",
      name: "Statutory Audit",
      summary: "Annual statutory audit for companies",
      longDescription: "Financial statement audit • Compliance verification • Audit report",
      basePriceInr: "19999",
      etaDays: 15,
      icon: "FileCheck",
      active: true,
    },
    {
      categoryId: categoryMap["risk-insurance"],
      slug: "gst-cancellation",
      name: "GST Cancellation",
      summary: "GST registration cancellation and closure",
      longDescription: "Application preparation • Final return filing • Cancellation certificate",
      basePriceInr: "1999",
      etaDays: 10,
      icon: "X",
      active: true,
    },
  ];

  await Promise.all(services.map((svc) => storage.createService(svc)));

  // Seed site content
  const siteContentItems: InsertSiteContent[] = [
    {
      key: "hero_title",
      section: "hero",
      label: "Hero Title",
      value: "Your Entire Business, Handled.",
      type: "text",
      description: "Main headline on the homepage hero section",
      sortOrder: 1,
    },
    {
      key: "hero_subtitle",
      section: "hero",
      label: "Hero Subtitle",
      value: "From idea to IMPACT. From concept to running brand. 300+ services. One platform.",
      type: "textarea",
      description: "Subtitle text on the homepage hero section",
      sortOrder: 2,
    },
    {
      key: "hero_cta_student",
      section: "hero",
      label: "Student CTA Button Text",
      value: "Student? Get Started",
      type: "text",
      description: "Call-to-action button text for students",
      sortOrder: 3,
    },
    {
      key: "hero_cta_business",
      section: "hero",
      label: "Business CTA Button Text",
      value: "Business? Explore Services",
      type: "text",
      description: "Call-to-action button text for businesses",
      sortOrder: 4,
    },
    {
      key: "hero_feature_1",
      section: "hero",
      label: "Feature 1",
      value: "Secure payments via Razorpay",
      type: "text",
      description: "First feature highlight below hero",
      sortOrder: 5,
    },
    {
      key: "hero_feature_2",
      section: "hero",
      label: "Feature 2",
      value: "India-first compliance",
      type: "text",
      description: "Second feature highlight below hero",
      sortOrder: 6,
    },
    {
      key: "hero_feature_3",
      section: "hero",
      label: "Feature 3",
      value: "300+ verified services",
      type: "text",
      description: "Third feature highlight below hero",
      sortOrder: 7,
    },
    {
      key: "about_title",
      section: "about",
      label: "About Section Title",
      value: "Why Stootap?",
      type: "text",
      description: "Title for the about/why choose us section",
      sortOrder: 1,
    },
    {
      key: "about_description",
      section: "about",
      label: "About Description",
      value: "We simplify business operations for Indian entrepreneurs and students. From registration to compliance, marketing to operations - everything you need in one place.",
      type: "textarea",
      description: "Description for the about section",
      sortOrder: 2,
    },
    {
      key: "footer_company_name",
      section: "footer",
      label: "Company Name",
      value: "Stootap",
      type: "text",
      description: "Company name displayed in footer",
      sortOrder: 1,
    },
    {
      key: "footer_tagline",
      section: "footer",
      label: "Footer Tagline",
      value: "Empowering entrepreneurs across India",
      type: "text",
      description: "Tagline displayed in footer",
      sortOrder: 2,
    },
    {
      key: "footer_copyright",
      section: "footer",
      label: "Copyright Text",
      value: "© 2025 Stootap. All rights reserved.",
      type: "text",
      description: "Copyright text in footer",
      sortOrder: 3,
    },
    {
      key: "services_title",
      section: "services",
      label: "Services Page Title",
      value: "Our Services",
      type: "text",
      description: "Main title on services page",
      sortOrder: 1,
    },
    {
      key: "services_subtitle",
      section: "services",
      label: "Services Page Subtitle",
      value: "Browse our complete catalog of business services",
      type: "text",
      description: "Subtitle on services page",
      sortOrder: 2,
    },
    {
      key: "contact_title",
      section: "contact",
      label: "Contact Page Title",
      value: "Get In Touch",
      type: "text",
      description: "Title on contact page",
      sortOrder: 1,
    },
    {
      key: "contact_description",
      section: "contact",
      label: "Contact Description",
      value: "Have questions? We're here to help. Fill out the form below and our team will get back to you within 24 hours.",
      type: "textarea",
      description: "Description on contact page",
      sortOrder: 2,
    },
  ];

  await Promise.all(siteContentItems.map((content) => storage.createSiteContent(content)));

  console.log(`✓ Seeded ${categories.length} categories and ${services.length} services`);
  console.log(`✓ Seeded ${siteContentItems.length} site content items`);
}
