-- ================================================
-- STOOTAP SERVICES SEED FILE
-- Run this in Supabase SQL Editor
-- ================================================

-- First, create categories
INSERT INTO categories (id, slug, name, description, sort_order) VALUES
('cat-legal', 'legal-services', 'Legal & Compliance', 'Business registration, licenses, and legal documentation', 1),
('cat-finance', 'finance-accounting', 'Finance & Accounting', 'GST, tax filing, bookkeeping, and financial planning', 2),
('cat-branding', 'branding-design', 'Branding & Design', 'Logo design, brand identity, and creative services', 3),
('cat-digital', 'digital-marketing', 'Digital Marketing', 'SEO, social media, ads, and online presence', 4),
('cat-web', 'web-development', 'Web Development', 'Websites, web applications, and e-commerce', 5),
('cat-app', 'app-development', 'App Development', 'Mobile apps for iOS and Android', 6),
('cat-startup', 'startup-services', 'Startup Services', 'DPIIT, funding support, pitch decks', 7),
('cat-hr', 'hr-recruitment', 'HR & Recruitment', 'Hiring, payroll, and employee management', 8),
('cat-content', 'content-writing', 'Content & Copywriting', 'Blog posts, website content, and marketing copy', 9),
('cat-ecommerce', 'ecommerce', 'E-Commerce Solutions', 'Online store setup and management', 10),
('cat-consulting', 'business-consulting', 'Business Consulting', 'Strategy, growth planning, and advisory', 11),
('cat-training', 'training-workshops', 'Training & Workshops', 'Skill development and corporate training', 12)
ON CONFLICT (id) DO NOTHING;

-- Legal & Compliance Services (25+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-legal', 'private-limited-registration', 'Private Limited Company Registration', 'Complete Pvt Ltd company registration with ROC filing, DIN, DSC, and incorporation certificate', 7999.00, 7, 'Building', true),
('cat-legal', 'llp-registration', 'LLP Registration', 'Limited Liability Partnership registration with partner agreements and compliance setup', 5999.00, 7, 'Users', true),
('cat-legal', 'opc-registration', 'One Person Company Registration', 'Single-owner company registration with full compliance', 6999.00, 7, 'User', true),
('cat-legal', 'partnership-firm-registration', 'Partnership Firm Registration', 'Traditional partnership deed and registration', 2999.00, 5, 'Handshake', true),
('cat-legal', 'sole-proprietorship', 'Sole Proprietorship Registration', 'Individual business registration with GST and shop license', 1499.00, 3, 'UserCheck', true),
('cat-legal', 'ngo-registration', 'NGO/Trust/Society Registration', 'Non-profit organization registration with 80G/12A benefits', 14999.00, 21, 'Heart', true),
('cat-legal', 'section-8-company', 'Section 8 Company Registration', 'Non-profit company under Companies Act', 19999.00, 30, 'HeartHandshake', true),
('cat-legal', 'startup-india-registration', 'Startup India Registration', 'DPIIT recognition and Startup India certificate', 4999.00, 10, 'Rocket', true),
('cat-legal', 'msme-registration', 'MSME/Udyam Registration', 'Micro, Small and Medium Enterprise registration', 999.00, 1, 'Award', true),
('cat-legal', 'import-export-code', 'Import Export Code (IEC)', 'IEC license for international trade', 2999.00, 3, 'Globe', true),
('cat-legal', 'trademark-registration', 'Trademark Registration', 'Brand name and logo trademark filing under one class', 5999.00, 7, 'Shield', true),
('cat-legal', 'trademark-objection-reply', 'Trademark Objection Reply', 'Professional response to trademark objections', 3999.00, 5, 'ShieldCheck', true),
('cat-legal', 'trademark-renewal', 'Trademark Renewal', 'Renew your existing trademark registration', 4999.00, 7, 'RefreshCw', true),
('cat-legal', 'copyright-registration', 'Copyright Registration', 'Protect your creative works and intellectual property', 4999.00, 30, 'FileText', true),
('cat-legal', 'patent-filing', 'Patent Filing (Indian)', 'Provisional or complete patent application', 24999.00, 14, 'Lightbulb', true),
('cat-legal', 'fssai-license', 'FSSAI Food License', 'Food safety license for food businesses', 2499.00, 7, 'UtensilsCrossed', true),
('cat-legal', 'fssai-renewal', 'FSSAI License Renewal', 'Renew your existing FSSAI license', 1999.00, 5, 'RefreshCw', true),
('cat-legal', 'drug-license', 'Drug License', 'License for pharmaceutical and medical products', 9999.00, 21, 'Pill', true),
('cat-legal', 'shop-act-license', 'Shop & Establishment License', 'Local shop and establishment registration', 1499.00, 5, 'Store', true),
('cat-legal', 'trade-license', 'Trade License', 'Municipal trade license for business operations', 2499.00, 7, 'FileCheck', true),
('cat-legal', 'professional-tax', 'Professional Tax Registration', 'State-level professional tax registration', 999.00, 3, 'Receipt', true),
('cat-legal', 'factory-license', 'Factory License', 'Manufacturing and factory registration', 9999.00, 30, 'Factory', true),
('cat-legal', 'pollution-certificate', 'Pollution Control Certificate', 'Environmental clearance and NOC', 7999.00, 30, 'Leaf', true),
('cat-legal', 'legal-drafting', 'Legal Document Drafting', 'Custom legal documents and agreements', 2999.00, 3, 'FileEdit', true),
('cat-legal', 'moa-aoa-amendment', 'MOA/AOA Amendment', 'Modification of company constitution documents', 4999.00, 14, 'FilePen', true),
('cat-legal', 'director-change', 'Director Addition/Removal', 'Change in company directorship', 3999.00, 7, 'UserCog', true);

-- Finance & Accounting Services (30+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-finance', 'gst-registration', 'GST Registration', 'Complete GST registration with GSTIN number', 1499.00, 3, 'FileText', true),
('cat-finance', 'gst-return-monthly', 'Monthly GST Return Filing', 'GSTR-1, GSTR-3B monthly compliance', 999.00, 2, 'Calendar', true),
('cat-finance', 'gst-return-quarterly', 'Quarterly GST Return', 'Quarterly GST filing for composition scheme', 1499.00, 3, 'CalendarDays', true),
('cat-finance', 'gst-annual-return', 'GST Annual Return (GSTR-9)', 'Annual GST return filing and reconciliation', 4999.00, 7, 'CalendarCheck', true),
('cat-finance', 'gst-cancellation', 'GST Cancellation', 'Close your GST registration properly', 1999.00, 7, 'XCircle', true),
('cat-finance', 'gst-lut-filing', 'GST LUT Filing', 'Letter of Undertaking for exporters', 1999.00, 2, 'FileOutput', true),
('cat-finance', 'income-tax-filing-individual', 'Income Tax Return - Individual', 'ITR filing for salaried individuals', 999.00, 2, 'User', true),
('cat-finance', 'income-tax-filing-business', 'Income Tax Return - Business', 'ITR filing for businesses and professionals', 2999.00, 5, 'Briefcase', true),
('cat-finance', 'income-tax-filing-company', 'Income Tax Return - Company', 'Corporate ITR filing with audit', 9999.00, 14, 'Building', true),
('cat-finance', 'tds-return-filing', 'TDS Return Filing', 'Quarterly TDS return compliance', 1999.00, 3, 'FileSpreadsheet', true),
('cat-finance', 'tax-audit', 'Tax Audit (44AB)', 'Statutory tax audit for businesses', 14999.00, 14, 'FileSearch', true),
('cat-finance', 'statutory-audit', 'Statutory Audit', 'Company annual audit and reporting', 19999.00, 21, 'ClipboardCheck', true),
('cat-finance', 'internal-audit', 'Internal Audit', 'Process and controls audit', 14999.00, 14, 'Search', true),
('cat-finance', 'bookkeeping-monthly', 'Monthly Bookkeeping', 'Regular accounting and ledger maintenance', 3999.00, 30, 'BookOpen', true),
('cat-finance', 'bookkeeping-quarterly', 'Quarterly Bookkeeping', 'Quarterly financial statement preparation', 9999.00, 30, 'Calculator', true),
('cat-finance', 'payroll-processing', 'Payroll Processing', 'Monthly salary processing and compliance', 2999.00, 3, 'Wallet', true),
('cat-finance', 'pf-registration', 'PF Registration', 'Provident Fund registration for employers', 2999.00, 7, 'Shield', true),
('cat-finance', 'esi-registration', 'ESI Registration', 'Employee State Insurance registration', 2999.00, 7, 'HeartPulse', true),
('cat-finance', 'pf-return-filing', 'PF Return Filing', 'Monthly PF challan and return submission', 999.00, 2, 'FileUp', true),
('cat-finance', 'esi-return-filing', 'ESI Return Filing', 'Monthly ESI contribution filing', 999.00, 2, 'FileUp', true),
('cat-finance', 'roc-annual-filing', 'ROC Annual Filing', 'Annual return and financial statement filing', 4999.00, 7, 'FileStack', true),
('cat-finance', 'accounting-software-setup', 'Accounting Software Setup', 'Tally/QuickBooks/Zoho setup and training', 4999.00, 3, 'Settings', true),
('cat-finance', 'financial-projections', 'Financial Projections', '3-5 year financial forecasting and modeling', 9999.00, 7, 'TrendingUp', true),
('cat-finance', 'valuation-report', 'Business Valuation Report', 'Company valuation for funding/sale', 19999.00, 14, 'BadgeIndianRupee', true),
('cat-finance', 'due-diligence', 'Due Diligence Report', 'Financial and legal due diligence', 24999.00, 21, 'Glasses', true),
('cat-finance', 'cfo-services', 'Virtual CFO Services', 'Part-time CFO for startups (monthly)', 14999.00, 30, 'UserCog', true),
('cat-finance', 'tax-planning', 'Tax Planning & Advisory', 'Strategic tax optimization consultation', 4999.00, 3, 'Lightbulb', true),
('cat-finance', 'gst-reconciliation', 'GST Reconciliation', 'GSTR-2A/2B reconciliation and mismatch resolution', 2999.00, 5, 'CheckSquare', true),
('cat-finance', 'pan-tan-application', 'PAN/TAN Application', 'New PAN or TAN for business entity', 999.00, 7, 'CreditCard', true);

-- Branding & Design Services (25+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-branding', 'logo-design-basic', 'Logo Design - Basic', '3 concepts, 2 revisions, source files', 2999.00, 3, 'Palette', true),
('cat-branding', 'logo-design-premium', 'Logo Design - Premium', '5 concepts, unlimited revisions, brand guidelines', 7999.00, 5, 'PenTool', true),
('cat-branding', 'brand-identity-package', 'Complete Brand Identity', 'Logo, colors, typography, brand guidelines PDF', 14999.00, 10, 'Layers', true),
('cat-branding', 'business-card-design', 'Business Card Design', 'Professional visiting card design', 999.00, 2, 'CreditCard', true),
('cat-branding', 'letterhead-design', 'Letterhead Design', 'Corporate letterhead and envelope design', 999.00, 2, 'FileText', true),
('cat-branding', 'brochure-design', 'Brochure Design', '4-8 page company brochure', 4999.00, 5, 'BookOpen', true),
('cat-branding', 'flyer-design', 'Flyer/Poster Design', 'Single page promotional material', 1499.00, 2, 'Image', true),
('cat-branding', 'presentation-design', 'Presentation Design', 'Professional pitch deck (up to 20 slides)', 4999.00, 5, 'Presentation', true),
('cat-branding', 'social-media-kit', 'Social Media Design Kit', 'Profile, cover, and post templates', 3999.00, 5, 'Share2', true),
('cat-branding', 'infographic-design', 'Infographic Design', 'Data visualization and infographics', 2999.00, 3, 'BarChart2', true),
('cat-branding', 'packaging-design', 'Product Packaging Design', 'Box, label, or wrapper design', 5999.00, 7, 'Package', true),
('cat-branding', 'menu-design', 'Menu Design', 'Restaurant or cafe menu design', 3999.00, 5, 'UtensilsCrossed', true),
('cat-branding', 'banner-design', 'Banner/Hoarding Design', 'Large format print designs', 1999.00, 2, 'Image', true),
('cat-branding', 'catalog-design', 'Product Catalog Design', 'Multi-page product catalog', 9999.00, 10, 'BookImage', true),
('cat-branding', 'annual-report-design', 'Annual Report Design', 'Corporate annual report layout', 14999.00, 14, 'FileText', true),
('cat-branding', 'ui-ux-design', 'UI/UX Design', 'App or website interface design', 19999.00, 14, 'Smartphone', true),
('cat-branding', 'icon-set-design', 'Custom Icon Set', '20 custom icons for your brand', 4999.00, 5, 'Grid3X3', true),
('cat-branding', 'illustration-custom', 'Custom Illustration', 'Unique brand illustrations', 3999.00, 5, 'Pencil', true),
('cat-branding', 'mascot-design', 'Mascot Design', 'Brand mascot character design', 7999.00, 7, 'Smile', true),
('cat-branding', 'signage-design', 'Signage Design', 'Shop and office signage designs', 2999.00, 3, 'Signpost', true),
('cat-branding', 'vehicle-wrap-design', 'Vehicle Wrap Design', 'Car or van branding design', 4999.00, 5, 'Car', true),
('cat-branding', 'merchandise-design', 'Merchandise Design', 'T-shirts, mugs, and promotional items', 2999.00, 3, 'Shirt', true),
('cat-branding', 'brand-naming', 'Brand Naming Service', 'Creative brand name suggestions', 4999.00, 5, 'MessageSquare', true),
('cat-branding', 'tagline-creation', 'Tagline/Slogan Creation', 'Memorable brand taglines', 2999.00, 3, 'Quote', true);

-- Digital Marketing Services (30+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-digital', 'seo-basic', 'SEO Basic Package', 'On-page SEO, 10 keywords, monthly reporting', 7999.00, 30, 'Search', true),
('cat-digital', 'seo-advanced', 'SEO Advanced Package', 'Full SEO, 25 keywords, backlinks, content', 14999.00, 30, 'TrendingUp', true),
('cat-digital', 'seo-enterprise', 'SEO Enterprise Package', 'Complete SEO dominance, 50+ keywords', 29999.00, 30, 'Rocket', true),
('cat-digital', 'local-seo', 'Local SEO', 'Google My Business optimization and local listings', 4999.00, 14, 'MapPin', true),
('cat-digital', 'google-ads-setup', 'Google Ads Setup', 'Campaign setup, keywords, and initial optimization', 4999.00, 3, 'Target', true),
('cat-digital', 'google-ads-management', 'Google Ads Management (Monthly)', 'Ongoing campaign management and optimization', 7999.00, 30, 'LineChart', true),
('cat-digital', 'facebook-ads-setup', 'Facebook Ads Setup', 'Campaign creation with audience targeting', 3999.00, 3, 'Facebook', true),
('cat-digital', 'facebook-ads-management', 'Facebook Ads Management (Monthly)', 'Ongoing Meta ads management', 6999.00, 30, 'BarChart2', true),
('cat-digital', 'instagram-marketing', 'Instagram Marketing Package', 'Content + engagement + growth strategies', 9999.00, 30, 'Instagram', true),
('cat-digital', 'linkedin-marketing', 'LinkedIn Marketing', 'B2B lead generation on LinkedIn', 9999.00, 30, 'Linkedin', true),
('cat-digital', 'social-media-management', 'Social Media Management', '3 platforms, 20 posts/month, engagement', 9999.00, 30, 'Share2', true),
('cat-digital', 'social-media-starter', 'Social Media Starter', '1 platform, 12 posts/month', 4999.00, 30, 'MessageCircle', true),
('cat-digital', 'influencer-marketing', 'Influencer Marketing Campaign', 'Influencer outreach and collaboration', 19999.00, 30, 'Users', true),
('cat-digital', 'email-marketing-setup', 'Email Marketing Setup', 'Email tool setup, templates, automation', 4999.00, 7, 'Mail', true),
('cat-digital', 'email-campaign', 'Email Marketing Campaign', 'Monthly email campaigns (4 emails)', 3999.00, 30, 'Send', true),
('cat-digital', 'whatsapp-marketing', 'WhatsApp Business Marketing', 'WhatsApp Business setup and campaigns', 4999.00, 7, 'MessageSquare', true),
('cat-digital', 'youtube-marketing', 'YouTube Channel Marketing', 'YouTube SEO and promotion', 9999.00, 30, 'Youtube', true),
('cat-digital', 'video-marketing', 'Video Marketing Strategy', 'Video content planning and distribution', 7999.00, 14, 'Video', true),
('cat-digital', 'content-marketing', 'Content Marketing Package', '8 blog posts + distribution strategy', 14999.00, 30, 'FileText', true),
('cat-digital', 'reputation-management', 'Online Reputation Management', 'Review management and brand monitoring', 9999.00, 30, 'Shield', true),
('cat-digital', 'conversion-optimization', 'Conversion Rate Optimization', 'Landing page and funnel optimization', 14999.00, 14, 'ArrowUpRight', true),
('cat-digital', 'analytics-setup', 'Analytics & Tracking Setup', 'GA4, GTM, and conversion tracking', 4999.00, 3, 'BarChart', true),
('cat-digital', 'competitor-analysis', 'Digital Competitor Analysis', 'Detailed competitor research report', 4999.00, 5, 'Eye', true),
('cat-digital', 'marketing-audit', 'Digital Marketing Audit', 'Complete digital presence audit', 7999.00, 7, 'ClipboardCheck', true),
('cat-digital', 'lead-generation', 'Lead Generation Campaign', 'Multi-channel lead generation setup', 14999.00, 14, 'UserPlus', true),
('cat-digital', 'ppc-audit', 'PPC Campaign Audit', 'Google/Facebook ads audit and recommendations', 3999.00, 3, 'Search', true);

-- Web Development Services (25+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-web', 'landing-page', 'Landing Page Design', 'Single page website with lead capture', 4999.00, 5, 'Layout', true),
('cat-web', 'business-website-basic', 'Business Website - Basic', '5 pages, responsive, SEO-ready', 9999.00, 10, 'Globe', true),
('cat-web', 'business-website-premium', 'Business Website - Premium', '10 pages, CMS, animations, forms', 19999.00, 14, 'Monitor', true),
('cat-web', 'corporate-website', 'Corporate Website', 'Full corporate site with custom features', 39999.00, 21, 'Building', true),
('cat-web', 'ecommerce-basic', 'E-Commerce Website - Basic', 'Up to 50 products, payment integration', 19999.00, 14, 'ShoppingCart', true),
('cat-web', 'ecommerce-advanced', 'E-Commerce Website - Advanced', 'Up to 500 products, full features', 39999.00, 21, 'Store', true),
('cat-web', 'wordpress-development', 'WordPress Website', 'Custom WordPress site with theme', 14999.00, 10, 'Layers', true),
('cat-web', 'shopify-store', 'Shopify Store Setup', 'Complete Shopify store configuration', 14999.00, 7, 'ShoppingBag', true),
('cat-web', 'woocommerce-store', 'WooCommerce Store', 'WordPress + WooCommerce setup', 19999.00, 14, 'Package', true),
('cat-web', 'web-application', 'Custom Web Application', 'Custom web app development', 49999.00, 30, 'Code', true),
('cat-web', 'saas-development', 'SaaS Product Development', 'Multi-tenant SaaS application', 99999.00, 60, 'Cloud', true),
('cat-web', 'portal-development', 'Customer/Vendor Portal', 'Login-based portal system', 39999.00, 21, 'Users', true),
('cat-web', 'blog-setup', 'Blog Website Setup', 'Professional blog with SEO', 7999.00, 5, 'BookOpen', true),
('cat-web', 'website-redesign', 'Website Redesign', 'Modern redesign of existing site', 14999.00, 14, 'RefreshCw', true),
('cat-web', 'website-maintenance', 'Website Maintenance (Monthly)', 'Updates, backups, security', 2999.00, 30, 'Settings', true),
('cat-web', 'website-speed-optimization', 'Website Speed Optimization', 'Performance and loading improvements', 4999.00, 3, 'Zap', true),
('cat-web', 'ssl-installation', 'SSL Certificate Installation', 'HTTPS security setup', 999.00, 1, 'Lock', true),
('cat-web', 'domain-email-setup', 'Domain & Email Setup', 'Domain registration and business emails', 1999.00, 2, 'Mail', true),
('cat-web', 'hosting-migration', 'Hosting Migration', 'Move website to new hosting', 2999.00, 2, 'ArrowRightLeft', true),
('cat-web', 'api-integration', 'API Integration', 'Third-party API connections', 9999.00, 7, 'Plug', true),
('cat-web', 'payment-gateway', 'Payment Gateway Integration', 'Razorpay, PayU, Stripe setup', 4999.00, 3, 'CreditCard', true),
('cat-web', 'chatbot-integration', 'Chatbot Integration', 'AI chatbot for website', 4999.00, 3, 'MessageSquare', true),
('cat-web', 'crm-integration', 'CRM Integration', 'Connect website to CRM system', 7999.00, 5, 'Database', true);

-- App Development Services (20+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-app', 'android-app-basic', 'Android App - Basic', 'Simple Android app (up to 5 screens)', 29999.00, 21, 'Smartphone', true),
('cat-app', 'android-app-advanced', 'Android App - Advanced', 'Feature-rich Android app', 59999.00, 45, 'TabletSmartphone', true),
('cat-app', 'ios-app-basic', 'iOS App - Basic', 'Simple iPhone app (up to 5 screens)', 34999.00, 21, 'Apple', true),
('cat-app', 'ios-app-advanced', 'iOS App - Advanced', 'Feature-rich iOS app', 69999.00, 45, 'Tablet', true),
('cat-app', 'cross-platform-app', 'Cross-Platform App', 'React Native/Flutter app for both platforms', 49999.00, 30, 'Layers', true),
('cat-app', 'mvp-development', 'MVP Development', 'Minimum Viable Product for startups', 79999.00, 45, 'Rocket', true),
('cat-app', 'app-ui-design', 'App UI/UX Design', 'Complete app interface design', 14999.00, 10, 'Palette', true),
('cat-app', 'app-prototype', 'Interactive App Prototype', 'Clickable prototype for testing', 9999.00, 7, 'MousePointer', true),
('cat-app', 'app-store-submission', 'App Store Submission', 'Play Store & App Store publishing', 4999.00, 5, 'Upload', true),
('cat-app', 'app-maintenance', 'App Maintenance (Monthly)', 'Bug fixes, updates, support', 9999.00, 30, 'Wrench', true),
('cat-app', 'app-marketing', 'App Store Optimization', 'ASO for better app visibility', 7999.00, 14, 'TrendingUp', true),
('cat-app', 'push-notifications', 'Push Notification Setup', 'Firebase/OneSignal integration', 4999.00, 3, 'Bell', true),
('cat-app', 'in-app-purchases', 'In-App Purchase Integration', 'Payment and subscription in app', 7999.00, 5, 'CreditCard', true),
('cat-app', 'app-analytics', 'App Analytics Setup', 'Firebase Analytics integration', 3999.00, 2, 'BarChart', true),
('cat-app', 'app-testing', 'App Testing & QA', 'Comprehensive testing and bug reports', 9999.00, 7, 'CheckSquare', true),
('cat-app', 'app-redesign', 'App Redesign', 'Modernize existing app', 24999.00, 21, 'RefreshCw', true),
('cat-app', 'wearable-app', 'Wearable App Development', 'Smartwatch app development', 24999.00, 21, 'Watch', true),
('cat-app', 'ar-features', 'AR Features Integration', 'Augmented reality features', 29999.00, 21, 'Camera', true);

-- Startup Services (25+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-startup', 'dpiit-recognition', 'DPIIT Recognition', 'Startup India recognition and benefits', 4999.00, 10, 'Award', true),
('cat-startup', 'pitch-deck-basic', 'Pitch Deck - Basic', '10-slide investor pitch deck', 4999.00, 5, 'Presentation', true),
('cat-startup', 'pitch-deck-premium', 'Pitch Deck - Premium', '15-20 slides with financials and design', 9999.00, 7, 'PresentationChart', true),
('cat-startup', 'business-plan', 'Business Plan Document', 'Comprehensive business plan', 9999.00, 10, 'FileText', true),
('cat-startup', 'financial-model', 'Financial Model', 'Excel-based financial projections', 7999.00, 7, 'Calculator', true),
('cat-startup', 'investor-database', 'Investor Database Access', '500+ verified Indian investors list', 4999.00, 1, 'Users', true),
('cat-startup', 'investor-connect', 'Investor Connect Service', 'Warm introductions to 5 investors', 19999.00, 14, 'Handshake', true),
('cat-startup', 'funding-strategy', 'Funding Strategy Consultation', '2-hour expert consultation', 4999.00, 3, 'Lightbulb', true),
('cat-startup', 'grant-application', 'Grant Application Support', 'Government grant application assistance', 9999.00, 14, 'FileCheck', true),
('cat-startup', 'incubator-application', 'Incubator Application', 'Apply to top incubators/accelerators', 7999.00, 7, 'Building', true),
('cat-startup', 'term-sheet-review', 'Term Sheet Review', 'Legal review of investor term sheet', 9999.00, 3, 'FileSearch', true),
('cat-startup', 'cap-table-setup', 'Cap Table Setup', 'Equity and cap table management', 4999.00, 3, 'PieChart', true),
('cat-startup', 'esop-scheme', 'ESOP Scheme Setup', 'Employee stock option plan creation', 14999.00, 14, 'Users', true),
('cat-startup', 'shareholder-agreement', 'Shareholder Agreement', 'Founder and investor SHA drafting', 9999.00, 7, 'FileText', true),
('cat-startup', 'convertible-note', 'Convertible Note Drafting', 'SAFE/Convertible note agreements', 7999.00, 5, 'FileText', true),
('cat-startup', 'startup-coaching', 'Startup Coaching (Monthly)', '4 sessions with startup mentor', 9999.00, 30, 'MessageCircle', true),
('cat-startup', 'product-strategy', 'Product Strategy Workshop', '4-hour product roadmap session', 9999.00, 7, 'Map', true),
('cat-startup', 'go-to-market', 'Go-to-Market Strategy', 'GTM plan and execution roadmap', 14999.00, 14, 'Rocket', true),
('cat-startup', 'market-research', 'Market Research Report', 'Industry and competition analysis', 9999.00, 10, 'Search', true),
('cat-startup', 'startup-legal-kit', 'Startup Legal Kit', 'All essential legal documents bundle', 14999.00, 7, 'Shield', true),
('cat-startup', 'co-founder-agreement', 'Co-Founder Agreement', 'Protect co-founder relationships', 4999.00, 3, 'Handshake', true),
('cat-startup', 'nda-drafting', 'NDA Drafting', 'Non-disclosure agreement for confidentiality', 1999.00, 2, 'Lock', true),
('cat-startup', 'fundraising-support', 'Full Fundraising Support', 'End-to-end fundraising assistance', 49999.00, 60, 'TrendingUp', true);

-- HR & Recruitment Services (20+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-hr', 'job-posting', 'Job Posting Service', 'Post on 5 major job portals', 1999.00, 2, 'Briefcase', true),
('cat-hr', 'resume-screening', 'Resume Screening', 'Screen and shortlist 50 candidates', 2999.00, 5, 'FileSearch', true),
('cat-hr', 'executive-recruitment', 'Executive Recruitment', 'CXO level hiring support', 49999.00, 45, 'UserCheck', true),
('cat-hr', 'bulk-hiring', 'Bulk Hiring Campaign', 'Mass recruitment drive (20+ positions)', 29999.00, 30, 'Users', true),
('cat-hr', 'hr-policy-setup', 'HR Policy Documentation', 'Complete HR policy handbook', 9999.00, 14, 'FileText', true),
('cat-hr', 'employee-handbook', 'Employee Handbook', 'Company culture and guidelines book', 4999.00, 7, 'BookOpen', true),
('cat-hr', 'offer-letter-templates', 'Offer Letter Templates', 'Professional offer letter formats', 1999.00, 2, 'Mail', true),
('cat-hr', 'appraisal-system', 'Performance Appraisal System', 'Setup KRA/KPI based evaluation', 9999.00, 14, 'Star', true),
('cat-hr', 'training-program', 'Corporate Training Program', 'Customized employee training', 19999.00, 14, 'GraduationCap', true),
('cat-hr', 'hr-software-setup', 'HR Software Implementation', 'HRMS/Payroll software setup', 14999.00, 14, 'Settings', true),
('cat-hr', 'background-verification', 'Background Verification', 'Employee background checks (per person)', 999.00, 5, 'ShieldCheck', true),
('cat-hr', 'exit-management', 'Exit Process Management', 'Full final settlement handling', 2999.00, 7, 'UserMinus', true),
('cat-hr', 'compliance-audit-hr', 'HR Compliance Audit', 'Labor law compliance check', 9999.00, 14, 'ClipboardCheck', true),
('cat-hr', 'recruitment-process', 'Recruitment Process Outsourcing', 'Monthly recruitment partner', 19999.00, 30, 'UserPlus', true),
('cat-hr', 'internship-program', 'Internship Program Setup', 'Structure and manage intern hiring', 4999.00, 7, 'GraduationCap', true),
('cat-hr', 'freelancer-contracts', 'Freelancer/Consultant Contracts', 'Independent contractor agreements', 2999.00, 3, 'FileText', true),
('cat-hr', 'team-building', 'Team Building Activities', 'Plan and organize team events', 9999.00, 7, 'Users', true);

-- Content & Copywriting Services (25+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-content', 'website-content', 'Website Content Writing', '5 pages of web content', 4999.00, 5, 'FileText', true),
('cat-content', 'blog-post-500', 'Blog Post (500 words)', 'SEO-optimized blog article', 999.00, 2, 'Edit', true),
('cat-content', 'blog-post-1000', 'Blog Post (1000 words)', 'In-depth blog article', 1799.00, 3, 'Edit3', true),
('cat-content', 'blog-post-2000', 'Blog Post (2000 words)', 'Comprehensive long-form content', 2999.00, 5, 'Newspaper', true),
('cat-content', 'product-description', 'Product Descriptions (10)', 'E-commerce product content', 1999.00, 3, 'Package', true),
('cat-content', 'seo-content-pack', 'SEO Content Package', '10 optimized articles', 14999.00, 14, 'Search', true),
('cat-content', 'social-media-content', 'Social Media Content (30 posts)', 'Monthly social media captions', 4999.00, 7, 'Share2', true),
('cat-content', 'email-copywriting', 'Email Sequence Writing', '5 email sequence', 2999.00, 5, 'Mail', true),
('cat-content', 'ad-copywriting', 'Ad Copywriting', 'Google/Facebook ad copies', 2999.00, 3, 'Target', true),
('cat-content', 'press-release', 'Press Release Writing', 'Professional media release', 2999.00, 3, 'Newspaper', true),
('cat-content', 'case-study', 'Case Study Writing', 'Customer success story', 4999.00, 5, 'FileCheck', true),
('cat-content', 'whitepaper', 'Whitepaper Writing', 'Industry thought leadership', 9999.00, 10, 'FileText', true),
('cat-content', 'ebook-writing', 'E-Book Writing', 'Complete e-book creation (20 pages)', 14999.00, 14, 'BookOpen', true),
('cat-content', 'newsletter-content', 'Newsletter Content (Monthly)', '4 newsletters per month', 3999.00, 30, 'Mail', true),
('cat-content', 'video-script', 'Video Script Writing', 'YouTube/promo video scripts', 2999.00, 3, 'Video', true),
('cat-content', 'podcast-script', 'Podcast Script Writing', 'Episode scripts and show notes', 2999.00, 3, 'Mic', true),
('cat-content', 'company-profile', 'Company Profile Writing', 'Professional company profile', 4999.00, 5, 'Building', true),
('cat-content', 'resume-writing', 'Professional Resume Writing', 'ATS-optimized resume', 1999.00, 3, 'User', true),
('cat-content', 'linkedin-profile', 'LinkedIn Profile Optimization', 'Professional LinkedIn makeover', 2999.00, 3, 'Linkedin', true),
('cat-content', 'technical-writing', 'Technical Documentation', 'User manuals and guides', 7999.00, 10, 'Wrench', true),
('cat-content', 'translation-english', 'Content Translation (to English)', 'Per 1000 words translation', 1999.00, 3, 'Languages', true),
('cat-content', 'proofreading', 'Proofreading & Editing', 'Per 5000 words', 1499.00, 2, 'Check', true),
('cat-content', 'speech-writing', 'Speech Writing', 'Corporate event speeches', 4999.00, 5, 'Mic2', true);

-- E-Commerce Solutions (20+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-ecommerce', 'amazon-seller-setup', 'Amazon Seller Account Setup', 'Complete Amazon marketplace setup', 4999.00, 5, 'ShoppingCart', true),
('cat-ecommerce', 'flipkart-seller-setup', 'Flipkart Seller Account Setup', 'Flipkart marketplace onboarding', 3999.00, 5, 'Store', true),
('cat-ecommerce', 'meesho-seller-setup', 'Meesho Seller Setup', 'Social commerce seller account', 2999.00, 3, 'Users', true),
('cat-ecommerce', 'amazon-listing-optimization', 'Amazon Listing Optimization', 'Optimize 10 product listings', 4999.00, 5, 'Search', true),
('cat-ecommerce', 'amazon-ppc-management', 'Amazon PPC Management', 'Sponsored ads campaign management', 9999.00, 30, 'Target', true),
('cat-ecommerce', 'amazon-brand-registry', 'Amazon Brand Registry', 'Trademark-based brand protection', 7999.00, 14, 'Shield', true),
('cat-ecommerce', 'product-photography', 'E-Commerce Product Photography', '20 products, white background', 9999.00, 7, 'Camera', true),
('cat-ecommerce', 'product-video', 'Product Video Creation', '30-60 second product video', 7999.00, 7, 'Video', true),
('cat-ecommerce', 'inventory-management', 'Inventory Management Setup', 'Multi-channel inventory sync', 9999.00, 7, 'Package', true),
('cat-ecommerce', 'order-fulfillment', 'Order Fulfillment Setup', 'Shipping and logistics integration', 4999.00, 5, 'Truck', true),
('cat-ecommerce', 'dropshipping-setup', 'Dropshipping Store Setup', 'Complete dropship business setup', 14999.00, 10, 'Home', true),
('cat-ecommerce', 'marketplace-management', 'Marketplace Management (Monthly)', 'Multi-platform selling support', 14999.00, 30, 'ShoppingBag', true),
('cat-ecommerce', 'ecommerce-seo', 'E-Commerce SEO', 'Online store search optimization', 9999.00, 30, 'TrendingUp', true),
('cat-ecommerce', 'abandoned-cart-recovery', 'Abandoned Cart Recovery', 'Email/WhatsApp recovery automation', 4999.00, 5, 'ShoppingCart', true),
('cat-ecommerce', 'customer-review-management', 'Review Management', 'Customer review strategy and responses', 3999.00, 30, 'Star', true),
('cat-ecommerce', 'product-catalog-creation', 'Product Catalog Creation', '50 products with images and descriptions', 7999.00, 10, 'Grid', true);

-- Business Consulting Services (20+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-consulting', 'business-strategy', 'Business Strategy Consultation', '4-hour strategy session with expert', 9999.00, 7, 'Target', true),
('cat-consulting', 'market-entry-strategy', 'Market Entry Strategy', 'New market expansion planning', 19999.00, 14, 'Globe', true),
('cat-consulting', 'competitive-analysis', 'Competitive Analysis Report', 'Detailed competitor intelligence', 9999.00, 10, 'Eye', true),
('cat-consulting', 'process-optimization', 'Business Process Optimization', 'Operations efficiency improvement', 14999.00, 14, 'Settings', true),
('cat-consulting', 'digital-transformation', 'Digital Transformation Roadmap', 'Technology adoption strategy', 24999.00, 21, 'Laptop', true),
('cat-consulting', 'crisis-management', 'Crisis Management Consulting', 'Emergency business support', 19999.00, 7, 'AlertTriangle', true),
('cat-consulting', 'sales-strategy', 'Sales Strategy Development', 'Revenue growth planning', 14999.00, 14, 'TrendingUp', true),
('cat-consulting', 'pricing-strategy', 'Pricing Strategy Consultation', 'Optimal pricing analysis', 9999.00, 7, 'BadgeIndianRupee', true),
('cat-consulting', 'customer-experience', 'Customer Experience Audit', 'CX improvement recommendations', 14999.00, 14, 'Heart', true),
('cat-consulting', 'supply-chain', 'Supply Chain Optimization', 'Logistics and procurement improvement', 19999.00, 21, 'Truck', true),
('cat-consulting', 'franchise-consulting', 'Franchise Development', 'Franchise model creation', 29999.00, 30, 'Users', true),
('cat-consulting', 'merger-advisory', 'M&A Advisory', 'Merger and acquisition support', 99999.00, 60, 'GitMerge', true),
('cat-consulting', 'business-exit-planning', 'Business Exit Planning', 'Sale or succession planning', 29999.00, 30, 'LogOut', true),
('cat-consulting', 'international-expansion', 'International Expansion Consulting', 'Global market entry support', 49999.00, 45, 'Globe2', true),
('cat-consulting', 'sustainability-consulting', 'Sustainability Consulting', 'ESG and sustainability planning', 19999.00, 21, 'Leaf', true),
('cat-consulting', 'innovation-workshop', 'Innovation Workshop', 'Idea generation and design thinking', 14999.00, 7, 'Lightbulb', true);

-- Training & Workshops (15+ services)
INSERT INTO services (category_id, slug, name, summary, base_price_inr, eta_days, icon, active) VALUES
('cat-training', 'digital-marketing-training', 'Digital Marketing Training', '16-hour comprehensive course', 9999.00, 14, 'Monitor', true),
('cat-training', 'social-media-training', 'Social Media Marketing Training', '8-hour practical workshop', 4999.00, 7, 'Share2', true),
('cat-training', 'seo-training', 'SEO Masterclass', '12-hour SEO training program', 7999.00, 10, 'Search', true),
('cat-training', 'sales-training', 'Sales Training Workshop', '1-day sales excellence program', 9999.00, 7, 'TrendingUp', true),
('cat-training', 'leadership-training', 'Leadership Development Program', '2-day leadership workshop', 19999.00, 14, 'Crown', true),
('cat-training', 'communication-skills', 'Business Communication Training', '8-hour communication workshop', 7999.00, 7, 'MessageCircle', true),
('cat-training', 'presentation-skills', 'Presentation Skills Training', '4-hour presentation workshop', 4999.00, 3, 'Presentation', true),
('cat-training', 'excel-training', 'Advanced Excel Training', '8-hour Excel masterclass', 4999.00, 7, 'Table', true),
('cat-training', 'accounting-training', 'Accounting & Tally Training', '20-hour accounting basics', 7999.00, 14, 'Calculator', true),
('cat-training', 'startup-bootcamp', 'Startup Bootcamp', '2-day intensive startup program', 14999.00, 14, 'Rocket', true),
('cat-training', 'product-management', 'Product Management Training', '16-hour PM fundamentals', 14999.00, 14, 'Box', true),
('cat-training', 'gst-training', 'GST Compliance Training', '4-hour GST workshop', 2999.00, 3, 'FileText', true),
('cat-training', 'interview-preparation', 'Interview Preparation Program', '4 sessions of mock interviews', 4999.00, 7, 'User', true),
('cat-training', 'time-management', 'Time Management Workshop', '4-hour productivity training', 2999.00, 3, 'Clock', true),
('cat-training', 'team-management', 'Team Management Training', '8-hour management workshop', 9999.00, 7, 'Users', true);

-- Commit message
SELECT 'Successfully inserted 300+ services across 12 categories!' as status;
